site_name: Hyperdrive Design
site_url: https://hyperdrivedesign.com

theme:
  name: material
  palette:
    scheme: slate
    primary: blue
    accent: cyan
  font:
    text: Roboto
    code: JetBrains Mono
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
    - media: "(prefers-color-scheme: light)"
      scheme: default
  logo: /assets/logo.svg
  favicon: /assets/favicon.svg
